version: "3.8"

services:
  local:
    image: nginx:alpine
    restart: unless-stopped 
    volumes:
      - /home/litt/local_web:/usr/share/nginx/html:ro
    networks: 
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.local.rule=Host(`192.168.0.150`)
      - traefik.http.routers.local.tls=false

networks:
  frontend:
    external: true

