version: "3.8"

services:
  project-zomboid:
    image: ghcr.io/cyrale/project-zomboid
    restart: unless-stopped
    environment:
      - SERVER_NAME=pzserver
      - PLAYER_PORTS=16262-16362
      - SERVER_PUBLIC_NAME
      - SERVER_PUBLIC_DESC
      - ADMIN_PASSWORD
      - RCON_PASSWORD
    ports:
      - 8766:8766/udp
      - 8767:8767/udp
      - 16261:16261/udp
      - 16262-16362:16262-16362
      - 27015:27015
    volumes:
      - /srv/project_zomboid:/server-data

