version: "3.8"
services:
  redbot:
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - /mnt/2tb/Docker/redbot/data:/data
    environment:
      - TOKEN
      - PREFIX=!
      - TZ=Europe/Moscow
      - PUID=1000
    labels:
      - homepage.group=Services
      - homepage.icon=mdi-robot-#990F02
      - homepage.name=Redbot
      - homepage.description=Discord bot
      - homepage.showStats=true


