version: "3.8"
services:
  redbot:
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - /mnt/2tb/Docker/redbot/data:/data
    environment:
      - TOKEN
      - PREFIX=!
      - TZ=Europe/Moscow
      - PUID=1000

