version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    environment:
      - DO_AUTH_TOKEN
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - frontend


networks:
  frontend:
    external: true

