version: "3.8"

services:
  socket_proxy:
    image: tecnativa/docker-socket-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - socket_proxy

  traefik:
    image: traefik:latest
    depends_on: 
      - socket_proxy
    restart: always
    environment:
      - DO_AUTH_TOKEN
      - CLOUDFLARE_DNS_API_TOKEN
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - $PWD/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - frontend
      - socket_proxy
    labels:
      - traefik.enable: true
      - traefik.http.middlewares.basic-auth.basicauth.users: $USERS
      - traefik.http.routers.traefik.service: api@internal
      - traefik.http.routers.traefik.middlewares: basic-auth
      - homepage.group: System
      - homepage.name: Traefik
      - homepage.href: https://traefik.$EXT_HOST
      - homepage.icon: traefik.png
      - homepage.description: Reverse proxy
      - homepage.widget.type: traefik
      - homepage.widget.url: http://traefik:8080

networks:
  frontend:
    external: true
  socket_proxy:

