services:
  socket_proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=0 
    networks:
      - default

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    depends_on:
      - socket_proxy
    volumes:
      - ./config:/app/config
      - /mnt:/mnt:ro
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=$EXT_HOST,www.$EXT_HOST
    networks:
      - frontend
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`$EXT_HOST`) || Host(`www.$EXT_HOST`)


networks:
  frontend:
    external: true

