version: "3.8"
services:
  ps3netsrv:
    image: shawly/ps3netsrv
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - USER_ID=1000
      - GROUP_ID=1000
    ports:
      - 38008:38008
    volumes:
      - /mnt/2tb/Games:/games:rw

