services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 8096:8096
      - 1900:1900/udp
      - 7359:7359/udp
    volumes:
      - ./data:/config
      - ./cache:/cache
      - /mnt:/mnt
    networks: 
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=https://jellyfin.$EXT_HOST
      - homepage.description=Media server
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://jellyfin.$EXT_HOST
      - homepage.widget.key=$API_KEY
      - homepage.widget.enableBlocks=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

networks:
  frontend:
    external: true
