version: "2.4"

services:
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=docker.${EXT_HOST}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=docker.${EXT_HOST}
    networks:
      - frontend
  agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: always 
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - agent_data:/data
    environment:
      - EDGE_KEY
      - EDGE
      - EDGE_ID

networks:
  frontend:
    external: true

volumes:
  data:
    name: portainer_data
  agent_data:
    name: portainer_agent_data
